version: '3.9'

services:
  backend:
    build: ./backend
    container_name: raft_backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: raft_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
